---
- hosts: all
  sudo: true
  tasks:
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install nginx
      apt:
        name: nginx
        state: present
    #- name: config nginx
      #apt: name=mysql-server state=present
    - name: Install python-pip
      apt: 
        name: python-pip 
        state: latest
    - name: Upgrade pip
      pip: 
        name: pip
        extra_args: --upgrade
    - name: Install docker-py
      pip: 
        name: docker-py
        state: latest
    - name: Launch chatroom container
      docker_container: 
        name: chatroom
        image: tumluliu/vagrant-chatroom
        command: sbt run
        state: started
        pull: true
        interactive: false
        tty: true
        detach: true
        ports: 
        - "9000:9000"
