---
- name: Launch chatroom container
  docker_container: 
    name: chatroom
    image: tumluliu/vagrant-chatroom
    command: sbt run
    state: started
    pull: true
    interactive: false
    tty: true
    detach: true
    ports: 
      - "{{ chatroom_port }}:{{ chatroom_port }}"
